export const TITLES = [
  { id: "card01", name: "사이버펑크", type: "anime", image: "/images/card-01.jpg", alt: "사이버펑크 포스터",
    keywords: ["SF","디스토피아","액션","사이버","청소년","여름"] },
  { id: "card02", name: "진격의 거인", type: "anime", image: "/images/card-02.jpg", alt: "진격의 거인 포스터",
    keywords: ["액션","다크","판타지","거인","전쟁"] },
  { id: "card03", name: "체인소맨", type: "anime", image: "/images/card-03.jpg", alt: "체인소맨 포스터",
    keywords: ["액션","다크","초현실","데빌헌터","청춘"] },
  { id: "card04", name: "최애의 아이", type: "anime", image: "/images/card-04.jpg", alt: "최애의 아이 포스터",
    keywords: ["아이돌","연예계","복수","드라마","로맨스","여름"] },
  { id: "card05", name: "주술회전", type: "anime", image: "/images/card-05.jpg", alt: "주술회전 포스터",
    keywords: ["액션","배틀","주술","학원"] },
  { id: "card06", name: "봇치더록", type: "anime", image: "/images/card-06.jpg", alt: "봇치더록 포스터",
    keywords: ["음악","밴드","코미디","청춘","여름"] },
  { id: "card07", name: "그 비스크 돌은 사랑을 한다", type: "anime", image: "/images/card-07.jpg", alt: "그 비스크 돌은 사랑을 한다 포스터",
    keywords: ["로맨스","학원","코스프레","일상","여름"] },
  { id: "card08", name: "푸른상자", type: "anime", image: "/images/card-08.jpg", alt: "푸른상자 포스터",
    keywords: ["로맨스","학원","체육관","배드민턴","여름"] },
  { id: "card09", name: "토라도라!", type: "anime", image: "/images/card-09.jpg", alt: "토라도라! 포스터",
    keywords: ["로맨스","학원","코미디","청춘","여름"] },
  { id: "card10", name: "스킵과 로퍼", type: "anime", image: "/images/card-10.jpg", alt: "스킵과 로퍼 포스터",
    keywords: ["일상","로맨스","학원","성장","여름"] },
  { id: "card11", name: "호리미야", type: "anime", image: "/images/card-11.jpg", alt: "호리미야 포스터",
    keywords: ["로맨스","학원","일상","청춘","여름"] },
  { id: "card12", name: "야마다 군과 Lv999의 사랑을 하다", type: "anime", image: "/images/card-12.jpg", alt: "야마다 군과 Lv999의 사랑을 하다 포스터",
    keywords: ["로맨스","게임","현실연애","여름"] },
  { id: "card13", name: "사이키쿠스오의 재난", type: "anime", image: "/images/card-13.jpg", alt: "사이키쿠스오의 재난 포스터",
    keywords: ["코미디","초능력","학원","일상"] },
  { id: "card14", name: "사카모토데이즈", type: "anime", image: "/images/card-14.jpg", alt: "사카모토데이즈 포스터",
    keywords: ["액션","암살자","코미디","일상"] },
  { id: "card15", name: "스파이패밀리", type: "anime", image: "/images/card-15.jpg", alt: "스파이패밀리 포스터",
    keywords: ["가족","첩보","코미디","일상"] },
  { id: "card16", name: "던전밥", type: "anime", image: "/images/card-16.jpg", alt: "던전밥 포스터",
    keywords: ["판타지","모험","요리","파티","코미디"] },
  { id: "card17", name: "장송의 프리렌", type: "anime", image: "/images/card-17.jpg", alt: "장송의 프리렌 포스터",
    keywords: ["판타지","여정","여운","성장","마법"] },
  { id: "card18", name: "식극의 소마", type: "anime", image: "/images/card-18.jpg", alt: "식극의 소마 포스터",
    keywords: ["요리","학원","배틀","코미디","여름"] },
];
